import random
from typing import Dict, List, Optional, Any
# Import the data model from the state.py file
from app.game.state import Player

class BunkerEngine:
    def __init__(self, api_key: str = ""):
        # Unique Gemini API key for this room
        self.api_key: str = api_key
        
        # Dictionary to maintain players (both connected and disconnected)
        self.players: Dict[str, Player] = {}
        self.host: Optional[str] = None
        
        # Game state variables
        self.game_phase: str = "lobby"
        self.player_roles: Dict[str, Dict] = {}
        self.current_scenario: str = ""
        self.game_language: str = "en"
        
        # Verdict variables
        self.secret_verdict: Optional[Dict] = None
        self.final_results: Optional[Dict] = None

    @property
    def active_player_names(self) -> List[str]:
        """Returns only the names of players with an active connection."""
        return [name for name, p in self.players.items() if p.is_connected]

    def connect_player(self, name: str, is_creator: bool = False) -> Player:
        """Registers a new player or reconnects an existing one."""
        if name in self.players:
            self.players[name].is_connected = True
        else:
            self.players[name] = Player(name=name)
            
        # Assign the host to the first player to join or if the frontend indicates they are the creator
        if not self.host or is_creator:
            self.host = name
            
        return self.players[name]

    def disconnect_player(self, name: str) -> None:
        """Marks a player as disconnected."""
        if name in self.players:
            self.players[name].is_connected = False
            
        # NOTE: We do not reassign the host. If the host reloads the page, 
        # their localStorage will allow them to regain control.

    def start_game(self, scenario: str, language: str) -> None:
        """Sets up the initial game data."""
        self.current_scenario = scenario
        self.game_language = language
        self.game_phase = "playing"

    def set_ai_roles(self, roles: Dict[str, Dict], secret_verdict: Dict) -> None:
        """Stores the configuration generated by the LLM."""
        self.player_roles = roles
        self.secret_verdict = secret_verdict

    def set_final_verdict(self, verdict_data: Dict) -> None:
        """Registers the AI's final verdict and advances the game phase."""
        self.final_results = verdict_data
        self.game_phase = "verdict"